[tool.poetry]
name = "jupyter-nix-kernel-ipython"
version = "0.1.1"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.10"
contourpy  = "1.0.7"
numpy = "^1.25"
ipykernel = "^6.25"
matplotlib = "3.6.3"
#pandas = "^2.0.0"
#meson-python = "^0.13.0"
#meson = "^1.2.0"
